version: '1'
services:
  manager:
    build:
      context: ./CrackHashManager
      dockerfile: Dockerfile
    ports:
      - "8080:8081"
    expose:
      - "8081"
    environment:
      - WORKER_DOMAIN=worker
      - MANAGER_PORT=8081
      - WORKER_PORT=8082
    networks:
      - crack-hash-network
      
  worker:
    build:
      context: ./CrackHashWorker
      dockerfile: Dockerfile
    expose:
      - "8082"
    environment:
      - MANAGER_DOMAIN=manager
      - MANAGER_PORT=8081
      - WORKER_PORT=8082
    networks:
      - crack-hash-network
networks:
  crack-hash-network:
    driver: bridge